# Numpy 

Numerical computing in Python

One of a few increasingly-popular, free competitors to MATLAB


___

## numpy.array

The main focus of this notebook will be numpy.array, numpy’s version of Python list.

numpy allows arrays of arbitrary dimension (1D, 2D, ...)



* 1. Creating NumPy Arrays
    * From python lists
    * Built-in Methods
* 2. Random numbers in numpy
* 3. Array Attributes and Methods
    * Reshape
    * max,min,argmax,argmin
    * shape
    * dtype
* 4. Numpy Indexing and Selection
* 5. NumPy Operations
___

In [7]:
import numpy as np

## 1. Creating NumPy Arrays

### From python lists
We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
a = np.array(my_list)
a

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
b = np.array(my_matrix)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### linspace
Return evenly spaced numbers over a specified interval.

In [8]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### zeros, ones, full

Generate arrays of zeros or ones or with constant values

In [10]:
np.zeros(3) # Create an array of all zeros

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3) # Create an array of all ones

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((3, 3), 7) # Create a constant array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### eye

Creates an identity matrix

In [15]:
np.eye(4) # Create a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##  2. Random numbers in numpy

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.11412087, 0.28693609])

In [18]:
np.random.rand(5,5)

array([[0.57176999, 0.6795968 , 0.49668842, 0.34696901, 0.25414265],
       [0.10491636, 0.38105232, 0.7199603 , 0.89816506, 0.45541485],
       [0.64669257, 0.53161878, 0.23126571, 0.16524098, 0.69855945],
       [0.21040409, 0.48516472, 0.1498871 , 0.43825869, 0.8474819 ],
       [0.30484881, 0.80772549, 0.32387833, 0.85652468, 0.35139859]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [19]:
np.random.randn(2)

array([-1.16433664, -0.92370661])

In [20]:
np.random.randn(5,5)

array([[-1.26090316, -0.54437444,  0.122636  ,  0.44430813,  0.14163813],
       [-0.45703099,  0.16509728,  0.37483409, -0.52698927, -0.63768165],
       [ 0.82968752,  1.15665178, -0.20990152,  0.16488727, -1.59023759],
       [ 0.24922422, -0.25676622, -1.49608354, -0.84802979, -0.00299769],
       [-1.25676308,  1.02590125, -1.82982738,  0.30428735,  1.57077596]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1,100)

9

In [22]:
np.random.randint(1,100,10)

array([ 2, 80, 35, 22, 15, 89, 60,  6, 26, 12])

## 3. Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([49,  7, 49,  9, 14, 39, 13, 32, 15, 13])

### reshape
Returns an array containing the same data with a new shape.

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [34]:
ranarr

array([49,  7, 49,  9, 14, 39, 13, 32, 15, 13])

In [35]:
ranarr.max()

49

In [36]:
ranarr.argmax()

0

In [37]:
ranarr.min()

7

In [38]:
ranarr.argmin()

1

### Shape

The two most basic properties of numpy array are `shape` and `dtype`. You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

Shape is an attribute that arrays have (not a method):

In [39]:
# Vector
arr.shape

(25,)

In [40]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [41]:
arr.reshape(1,25).shape

(1, 25)

In [43]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [44]:
arr.dtype

dtype('int64')

## 4. NumPy Indexing and Mask

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [36]:
#Creating sample array
arr = np.arange(0,11)

In [37]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing 
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [38]:
#Get a value at an index
arr[8]

8

In [39]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

### Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [49]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [50]:
# Getting individual element value
arr_2d[1,0]

20

In [51]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Boolean mask


Let's briefly go over how to use brackets for selection based off of comparison operators.

In [59]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
bool_arr = arr > 4

In [62]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## 5. NumPy Operations

### Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [66]:
import numpy as np
arr = np.arange(0,10)

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [73]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
np.max(arr) #same as arr.max()

9

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 

In [107]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(f"x.shape = {x.shape}, v.shape={v.shape}")
y = x + v  # Add v to each row of x using broadcasting
y

x.shape = (4, 3), v.shape=(3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).
